
$fg = rgb(ebdbb2)
$bg = rgb(282828)
$bg_h= rgb(1d2021)
$gray = rgb(928374)
$red = rgb(fb4934)
$green = rgb(b8bb26)
$yellow = rgb(fabd2f)
$blue = rgb(83a598)
$purple = rgb(d3869b)
$aqua = rgb(8ec07c)
$orange = rgb(fe8019)
