"""
389. Find the Difference(*)(DICT)
=========================
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position

Return the letter that was added to t.

Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:
Input: s = "", t = "y"
Output: "y"
"""


def findTheDifference(s: str, t: str) -> str:
    sum = 0
    for ct in t:
        sum += ord(ct)
    for cs in s:
        sum -= ord(cs)

    return chr(sum)


def findTheDifference1(s: str, t: str) -> str:
    sDict = {}
    tDict = {}
    for c in s:
        sDict[c] = sDict.get(c, 0) + 1
    for c in t:
        tDict[c] = tDict.get(c, 0) + 1

    for k, v in tDict.items():
        if k in sDict and sDict[k] != tDict[k]:
            return k
        if k not in sDict:
            return k


s, t = "abcd", "abcde"
# s, t = "", "y"
print(findTheDifference(s, t))
